---
- name: Elastic and Kibana download and setup
  hosts: all
  remote_user: ansible
  become: true

  handlers:
    - name: restart elastic
      ansible.builtin.systemd_service:
        name: elasticsearch
        state: restarted

  tasks:
    - name: Apt Install gpg Support Packages 
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - gnupg

    - name: Get Elastic Keyring to verify Elastic download
      # `-qO -` outputs the file to stdout, which can then be used by gpg
      ansible.builtin.shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
      args: { creates: /usr/share/keyrings/elastic-keyring.gpg }

    - name: Signal the Signing of Elastic during use
      ansible.builtin.template:
        src: elastic-9.x.list.j2
        dest: /etc/apt/sources.list.d/elastic-9.x.list

    - name: Apt Install Elastic (v9.5)
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - elasticsearch=9.5.0

    - name: Configure JVM heap size
      ansible.builtin.template:
        src: heap.options.j2
        dest: /etc/elasticsearch/jvm.options.d/heap.options
      notify: restart elastic

