---
- name: Fleet Server Setup
  hosts: siem
  remote_user: ansible
  become: true

  tasks:
    - name: Create Agent Policy for Fleet Server
      ansible.builtin.uri:
        url: "http://{{ elastic_host }}:5601/api/fleet/agent_policies"
        method: POST
        user: elastic
        password: "{{ vault_elastic_password }}"
        validate_certs: false
        force_basic_auth: true
        headers:
          kbn-xsrf: "true"
        body_format: json
        body:
          name: "Fleet Server Policy"
          namespace: "default"
          has_fleet_server: true
        status_code: 200
      register: fleet_server_policy
      ignore_errors: true

    - name: Check service account tokens
      ansible.builtin.command: /usr/share/elasticsearch/bin/elasticsearch-service-tokens list
      register: token_list

    - name: Generate Fleet Server service token
      ansible.builtin.command: >
        /usr/share/elasticsearch/bin/elasticsearch-service-tokens create elastic/fleet-server fleet-server-token
      register: fleet_service_token_output
      when: "'elastic/fleet-server/fleet-server-token' not in token_list.stdout"

    - name: Split token output
      ansible.builtin.set_fact:
        fleet_service_token_list: "{{ fleet_service_token_output.stdout | split }}"

    - name: Clean token output
      ansible.builtin.set_fact:
        fleet_service_token: "{{ fleet_service_token_list[-1] | trim }}"

    - name: Check if Elastic Agent is Installed
      ansible.builtin.stat:
        path: /opt/elastic-agent-9.5.0-linux-x86_64
      register: elastic_agent_downloaded

    - name: Download Elastic Agent
      ansible.builtin.unarchive:
        src: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-9.5.0-linux-x86_64.tar.gz"
        dest: /opt
        remote_src: true
        creates: /opt/elastic-agent-9.5.0-linux-x86_64
      when: not elastic_agent_downloaded.stat.exists 

    - name: Check if Fleet Server is already installed
      ansible.builtin.stat:
        path: /opt/Elastic/Agent/elastic-agent
      register: fleet_server_installed

    - name: Install and start Fleet Server
      ansible.builtin.command: >
        /opt/elastic-agent-9.5.0-linux-x86_64/elastic-agent install
        --fleet-server-es=http://{{ elastic_host }}:5601
        --fleet-server-service-token={{ fleet_service_token }}
        --fleet-server-policy={{ fleet_server_policy.json.item.id }}
        --fleet-server-es-ca=/etc/elasticsearch/certs/http_ca.crt
        --non-interactive
      when: not fleet_server_installed.stat.exists    

